### ISSUE TITLE
feat: product 초기 설정 및 CRUD

### ISSUE THREAD

**Issue by JihyeChu** [jv-cc/FlowMesh#49]
## Description
상품 서비스의 기본 환경 구성 및 초기 설정 작업과 상품 항목의 확장 및 관리할 수 있도록 합니다.

## Todo
- [x] DDD 아키텍처 반영
- [x] errorException 반영
- [x] swagger 적용
- [x] 상품 생성 기능 구현
- [x] 상품 수정 기능 구현
- [x] 상품 삭제 기능 구현
- [x] 상품 단건 조회 기능 구현

## ETC
