### ISSUE TITLE
refactor: 코드 리팩토링

### ISSUE THREAD

**Issue by JISU-YANG** [jv-cc/FlowMesh#53]
## Description
기능 구현이 완료 되어 점검 및 리팩토링을 진행합니다.

## Todo
- [x] 로그 정리
- [x] 불필요한 어노테이션 정리
- [x] Enum 필드 속성 정리
- [ ] Swagger API 문서 작성

## ETC
-
