### ISSUE TITLE
feat: Hub Movement Info 초기 설정 및 생성 기능 추가

### ISSUE THREAD

**Issue by JihyeChu** [jv-cc/FlowMesh#64]
## Description
출발 허브와 도착 허브를 입력하여 허브간 이동정보를 생성합니다. 

## Todo
- [x] 허브간 이동 정보 entity 생성
- [ ] 허브간 이동 정보 생성 기능 
- [ ] 허브간 이동 정보 반환

## ETC
