### ISSUE TITLE
chore: Delivery 서비스 환경 초기 설정

### ISSUE THREAD

**Issue by Kim-Yeongho** [jv-cc/FlowMesh#8]
## Description
Delivery 서비스 환경 초기 설정

## Todo
- [x] Initializr 생성
- [x] gradle 의존성 추가
- [x] yml 파일 추가
- [x] Eureka Client 설정
- [x] 패키지 구조 생성
- [x] Controller 생성
- [x] Service 생성
- [x] dto 생성
- [x] enum 생성
- [x] entity 생성
- [x] Repository 생성
- [x] Exception 생성
- [ ] Swagger 추가

## ETC
기타사항
